from enum import Enum


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_RATE_LIMIT = "WAITING_RATE_LIMIT"
    WAITING_BUDGET_APPROVAL = "WAITING_BUDGET_APPROVAL"
    WAITING_SAFETY_REVIEW = "WAITING_SAFETY_REVIEW"
    WAITING_PARSE_REVIEW = "WAITING_PARSE_REVIEW"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    REPLAN_REQUIRED = "REPLAN_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CORRUPTED = "CORRUPTED"


class AgentName(str, Enum):
    RESEARCHER = "Researcher"
    PLANNER = "Planner"
    ITINERARY = "Itinerary"
    VALIDATOR = "Validator"
    REPORTER = "Reporter"
